name: Set up Algolia

on:
  push:
    branches:
      - main

jobs:
  set-up-algolia:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Initialize Firebase Functions Locally
        run: |
          mkdir functions
          cd functions
          npm init -y
          npm install firebase-functions firebase-admin
          echo 'const functions = require("firebase-functions"); module.exports = functions;' > index.js
        working-directory: .

      - name: Install Algolia
        run: npm install algoliasearch
        working-directory: ./functions

      - name: Add Local Firebase Config (without Firebase account)
        run: |
          echo "{
            \"algolia\": {
              \"app\": \"2PXKHTUY75\",
              \"key\": \"6fd704d4826d800bcc172af8f11a2c55\"
            }
          }" > .runtimeconfig.json
        working-directory: ./functions

      - name: Create firebase.json Configuration
        run: |
          echo '{
            "functions": {
              "source": "functions"
            }
          }' > firebase.json

      - name: Run Firebase Functions Emulator (Demo Mode)
        run: |
          firebase emulators:start --only functions --project demo-project
        working-directory: .

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated: $(date -u +"%D %T %Z")" --allow-empty
          git push origin HEAD:main
